login (landing page) and create new user page
tylercodes1/Team7ProjectRepo pull request #12
Opened 2020-12-20 23:34 UTC by MacyMcAnally

Please review this login branch for Login (landing page) and create new user page!

2020-12-22 22:02 UTC, tylercodes1 requested changes
Styling is pretty good, may not need to change it later. Please review the comments for structural changes

2020-12-22 22:02 UTC, tylercodes1 commented on .eslintcache
> -[{"C:\\Users\\dexlu\\OneDrive\\Desktop\\Training\\Project2\\Team7ProjectRepo\\src\\index.js":"1","C:\\Users\\dexlu\\OneDrive\\Desktop\\Training\\Project2\\Team7ProjectRepo\\src\\reportWebVitals.js":"
add .eslintcache to the .gitignore

2020-12-22 22:02 UTC, tylercodes1 commented on src/App.css
> +}
Please revert css of App.css back to it's original styling (red)

2020-12-22 22:02 UTC, tylercodes1 commented on src/pages/LoginPage.js
> +        <div className="login">
please rename the class to "login-page" and change the according css mapping

2020-12-22 22:02 UTC, tylercodes1 commented on src/pages/CreateNewUserPage.js
> +        <div className="newuser">
change className to "newuser-page" and change the according css mapping

2020-12-22 22:02 UTC, tylercodes1 commented on src/pages/FormStyle.css
> +    margin-left: 600px;
No changes here, but we will change how this is rendered on the screen to be "responsive-design"

2020-12-22 22:02 UTC, tylercodes1 commented on src/pages/CreateNewUserPage.js
> +import React from 'react';
Please change the file structure as follows
>src
>>pages
>>>LoginPage
>>>>LoginPage.js
>>>>LoginPage.css

>>>CreateNewUserPage
>>>>CreateNewUserPage.js
>>>>CreateNewUserPage.css

2020-12-23 00:47 UTC, MacyMcAnally commented on src/pages/LoginPage.js
> +        <div className="login">
Do you mean the classname in the div tag?

2020-12-23 02:11 UTC, MacyMcAnally commented
Please review! Thank you!

2020-12-23 03:04 UTC, tylercodes1 approved these changes
Nice work!

2020-12-28 05:54 UTC, MacyMcAnally commented
Hey @tylercodes1, I brought in the latest changes in main and cleaned up my history with rebase. Is everything ok to merge still?

2020-12-28 15:17 UTC, merged